document.writeln("<!--用来生成js文件-->");
document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'utf-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'>");
document.writeln("    <script src=\'../js/jquery-1.8.0.js\'></script>");
document.writeln("    <link rel=\'stylesheet\' href=\'../js/layui/css/layui.css\'>");
document.writeln("    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->");
document.writeln("    <!--[if lt IE 9]>");
document.writeln("    <script src=\'../js/html5shiv.min.js\'></script>");
document.writeln("    <script src=\'../js/respond.min.js\'></script>");
document.writeln("    <script src=\'../js/PIE/PIE.js\'></script>");
document.writeln("    <![endif]-->");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/base.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/reset.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/page/head.css\'>");
document.writeln("    <script src=\'../js/layui/layui.js\'></script>");
document.writeln("    <script src=\'../js/page/public_head.js\'></script>");
document.writeln("    <link rel=\'stylesheet\' href=\'../icon/iconfont.css\'>");
document.writeln("    <script src=\'../icon/iconfont.js\'></script>");
document.writeln("    <script src=\'http://pv.sohu.com/cityjson?ie=utf-8\'></script>");
document.writeln("    <script src=\'../js/commen.js\'></script>");
document.writeln("    <style>");
document.writeln("        .headinp-inp, .headinp-inp input, .headinp-btn, .layui-layer-login.layui-layer {");
document.writeln("            behavior: url(../js/PIE/PIE.htc);");
document.writeln("            position: relative;");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div class=\'head-box\'>");
document.writeln("    <div class=\'head-bar layui-row\'>");
document.writeln("        <div class=\'headBar-inner layui-col-md-offset2 layui-col-md8\'>");
document.writeln("            <div class=\'fl leftTop\'>欢迎您登录预约诊疗服务平台</div>");
document.writeln("            <div class=\'fr\'>");
document.writeln("                <div class=\'fl login-box weilogin\'>");
document.writeln("                    请");
document.writeln("                    <span class=\'blue cursorP\' id=\'loginBtn\'>登录</span>");
document.writeln("                    或");
document.writeln("                    <span class=\'blue cursorP\' id=\'registerBtn\'>注册</span>");
document.writeln("                </div>");
document.writeln("                <div class=\'fl login-box yilogin cursorP\'>");
document.writeln("                    <span class=\'blue username\'>13012345678</span>");
document.writeln("                    <ul class=\'login-ul\'>");
document.writeln("                        <li class=\'login-li\' id=\'logout\'>退出</li>");
document.writeln("                        <!--<li class=\'login-li\'>退出哈哈哈哈哈哈</li>-->");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'fl dingdan-box cursorP\' id=\'dingdanBtn\'>订单信息</div>");
document.writeln("            </div>");
document.writeln("            <div class=\'clear\'></div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'head-tit layui-row\'>");
document.writeln("        <div class=\'headTit-inner layui-col-md-offset2 layui-col-md8\'>");
document.writeln("            <div class=\'fl headTit-left\'>");
document.writeln("                <div class=\'logo fl\'>");
document.writeln("                    <img src=\'../img/logo.png\' alt=\'\'>");
document.writeln("                </div>");
document.writeln("                <div class=\'tit-txt fl\'>");
document.writeln("                    <div class=\'head-tit-bg\'>预约诊疗服务平台</div>");
document.writeln("                    <div class=\'head-tit-sm\'>预约诊疗服务平台</div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'fr headTit-right layui-row\'>");
document.writeln("                <ul class=\'headinp-tab\'>");
document.writeln("                    <li class=\'fl\' code=\'0\'>");
document.writeln("                        医院");
document.writeln("                        <img src=\'../img/search_select.png\' alt=\'\'>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'fl\' code=\'1\'>");
document.writeln("                        医生");
document.writeln("                        <img src=\'../img/search_select.png\' alt=\'\'>");
document.writeln("                    </li>");
document.writeln("                    <!--<li class=\'clear\'></li>-->");
document.writeln("                </ul>");
document.writeln("                <div class=\'layui-row\'>");
document.writeln("                    <div class=\'headinp-box\'>");
document.writeln("                        <div class=\'headinp-inp\'>");
document.writeln("                            <input type=\'text\' id=\'searchInp\'>");
document.writeln("                        </div>");
document.writeln("                        <div class=\'headinp-btn layui-col-md2\' id=\'searchBtn\'>");
document.writeln("                            搜索");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'clear\'></div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'head-tab layui-row\'>");
document.writeln("        <div class=\'headTab-inner layui-col-md-offset2 layui-col-md8\'>");
document.writeln("            <ul class=\'headTab-ul\'>");
document.writeln("                <li>");
document.writeln("                    网站首页");
document.writeln("                    <img src=\'../img/icon_select_white.png\' alt=\'\'>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    预约挂号");
document.writeln("                    <img src=\'../img/icon_select_white.png\' alt=\'\'>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    个人中心");
document.writeln("                    <img src=\'../img/icon_select_white.png\' alt=\'\'>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    健康科普");
document.writeln("                    <img src=\'../img/icon_select_white.png\' alt=\'\'>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    预约指南");
document.writeln("                    <img src=\'../img/icon_select_white.png\' alt=\'\'>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");